export const COSPLAYER_TAGS = [
  {
    id: "genresUnivers",
    name: "Genres & Univers",
    icon: "🎭",
    tags: [
      { id: "anime", name: "Anime", icon: "🎌" },
      { id: "manga", name: "Manga", icon: "📚" },
      { id: "jeuxVideo", name: "Jeux Vidéo", icon: "🎮" },
      { id: "comics", name: "Comics", icon: "📕" },
      { id: "marvel", name: "Marvel", icon: "🦸" },
      { id: "dcComics", name: "DC Comics", icon: "🦇" },
      { id: "fantasy", name: "Fantasy", icon: "🧙" },
      { id: "scienceFiction", name: "Science Fiction", icon: "🚀" },
      { id: "horreur", name: "Horreur", icon: "👻" },
      { id: "disney", name: "Disney", icon: "🏰" },
      { id: "studioGhibli", name: "Studio Ghibli", icon: "🐱" },
      { id: "kpop", name: "K-Pop", icon: "🎤" },
      { id: "jpop", name: "J-Pop", icon: "🎵" },
      { id: "webtoon", name: "Webtoon", icon: "📱" },
    ],
  },
  {
    id: "stylesCosplay",
    name: "Styles de cosplay",
    icon: "🧑‍🎤",
    tags: [
      { id: "cosplayArmor", name: "Cosplay Armor", icon: "🛡️" },
      { id: "cosplayMakeup", name: "Cosplay Makeup", icon: "💄" },
      { id: "crossplay", name: "Crossplay", icon: "⚧️" },
      { id: "genderbend", name: "Genderbend", icon: "🔄" },
      { id: "originalCharacter", name: "Original Character", icon: "✨" },
      { id: "casualCosplay", name: "Casual Cosplay", icon: "👕" },
      { id: "props", name: "Props", icon: "🗡️" },
      { id: "cosplayWig", name: "Cosplay Wig", icon: "💇" },
      { id: "cosplayCrafting", name: "Cosplay Crafting", icon: "🔨" },
      { id: "performanceCosplay", name: "Performance Cosplay", icon: "🎭" },
      { id: "groupCosplay", name: "Group Cosplay", icon: "👥" },
      { id: "cosplayCouple", name: "Cosplay Couple", icon: "💑" },
    ],
  },
  {
    id: "niveauExperience",
    name: "Niveau d'expérience",
    icon: "🧵",
    tags: [
      { id: "beginnerCosplayer", name: "Beginner Cosplayer", icon: "🌱" },
      { id: "intermediateCosplayer", name: "Intermediate Cosplayer", icon: "🌿" },
      { id: "proCosplayer", name: "Pro Cosplayer", icon: "🌳" },
      { id: "veteranCosplayer", name: "Veteran Cosplayer", icon: "🏆" },
    ],
  },
  {
    id: "conventionsEvenements",
    name: "Conventions & Événements",
    icon: "📍",
    tags: [
      { id: "japanExpo", name: "Japan Expo", icon: "🇯🇵" },
      { id: "comicCon", name: "Comic Con", icon: "🦸" },
      { id: "miaCon", name: "MIA Con", icon: "🎪" },
      { id: "madeInAsia", name: "Made In Asia", icon: "🏯" },
      { id: "factsBelgium", name: "Facts Belgium", icon: "🇧🇪" },
      { id: "cosplayContest", name: "Cosplay Contest", icon: "🏅" },
      { id: "photoshootReady", name: "Photoshoot Ready", icon: "📸" },
    ],
  },
  {
    id: "photographieCollaboration",
    name: "Photographie / Collaboration",
    icon: "📸",
    tags: [
      { id: "openToPhotoshoot", name: "Open To Photoshoot", icon: "📷" },
      { id: "lookingForPhotographer", name: "Looking For Photographer", icon: "🔍" },
      { id: "tfpCosplay", name: "TFP Cosplay", icon: "🤝" },
      { id: "cosplayCollab", name: "Cosplay Collab", icon: "👯" },
      { id: "trustAndShootVerified", name: "Trust And Shoot Verified", icon: "✅" },
      { id: "modelReleaseOK", name: "Model Release OK", icon: "📝" },
      { id: "cosplayInStudio", name: "Cosplay In Studio", icon: "🏢" },
      { id: "cosplayOutdoor", name: "Cosplay Outdoor", icon: "🌳" },
    ],
  },
  {
    id: "creationSavoirFaire",
    name: "Création et savoir-faire",
    icon: "🎨",
    tags: [
      { id: "selfMadeCosplay", name: "Self Made Cosplay", icon: "🧵" },
      { id: "commissionedCosplay", name: "Commissioned Cosplay", icon: "💰" },
      { id: "3dPrintedProps", name: "3D Printed Props", icon: "🖨️" },
      { id: "sewingSkills", name: "Sewing Skills", icon: "🧶" },
      { id: "foamSmith", name: "Foam Smith", icon: "🧩" },
      { id: "wigStyling", name: "Wig Styling", icon: "💇" },
      { id: "makeupArtist", name: "Makeup Artist", icon: "🎭" },
      { id: "armorBuilding", name: "Armor Building", icon: "🛡️" },
      { id: "embroideryDetails", name: "Embroidery Details", icon: "🧵" },
    ],
  },
]
